<?php
/**
 * CallbackEventType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * CallbackEventType Class Doc Comment
 *
 * @category Class
 * @description Events that can trigger a webhook callback: - workflow.completed: All jobs done successfully - workflow.failed: At least one job failed, none in progress - workflow.partially_failed: Some succeeded, some failed - operation.completed: Individual operation done (opt-in for granular progress)
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CallbackEventType
{
    /**
     * Possible values of this enum
     */
    public const WORKFLOW_COMPLETED = 'workflow.completed';

    public const WORKFLOW_FAILED = 'workflow.failed';

    public const WORKFLOW_PARTIALLY_FAILED = 'workflow.partially_failed';

    public const OPERATION_COMPLETED = 'operation.completed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WORKFLOW_COMPLETED,
            self::WORKFLOW_FAILED,
            self::WORKFLOW_PARTIALLY_FAILED,
            self::OPERATION_COMPLETED
        ];
    }
}


