<?php
/**
 * ContactSubject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * ContactSubject Class Doc Comment
 *
 * @category Class
 * @description Subject category: - general_enquiry: General questions - bug_report: Report a bug or issue - suggestion: Feature suggestion or improvement idea - complaint: Complaint about the service - business_enquiry: Business or partnership enquiry
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactSubject
{
    /**
     * Possible values of this enum
     */
    public const GENERAL_ENQUIRY = 'general_enquiry';

    public const BUG_REPORT = 'bug_report';

    public const SUGGESTION = 'suggestion';

    public const COMPLAINT = 'complaint';

    public const BUSINESS_ENQUIRY = 'business_enquiry';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GENERAL_ENQUIRY,
            self::BUG_REPORT,
            self::SUGGESTION,
            self::COMPLAINT,
            self::BUSINESS_ENQUIRY
        ];
    }
}


