<?php
/**
 * MultipartInitiateResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;

use \ArrayAccess;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * MultipartInitiateResponse Class Doc Comment
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MultipartInitiateResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MultipartInitiateResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'file_id' => 'string',
        'mime_type' => 'string',
        'first_chunk_etag' => 'string',
        'first_chunk_size_bytes' => 'int',
        'total_parts' => 'int',
        'recommended_chunk_size' => 'int',
        'presigned_urls' => '\Gisl\Generated\OpenApi\Model\PresignedUrlPart[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'file_id' => 'uuid',
        'mime_type' => null,
        'first_chunk_etag' => null,
        'first_chunk_size_bytes' => null,
        'total_parts' => null,
        'recommended_chunk_size' => null,
        'presigned_urls' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'file_id' => false,
        'mime_type' => false,
        'first_chunk_etag' => false,
        'first_chunk_size_bytes' => false,
        'total_parts' => false,
        'recommended_chunk_size' => false,
        'presigned_urls' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_id' => 'file_id',
        'mime_type' => 'mime_type',
        'first_chunk_etag' => 'first_chunk_etag',
        'first_chunk_size_bytes' => 'first_chunk_size_bytes',
        'total_parts' => 'total_parts',
        'recommended_chunk_size' => 'recommended_chunk_size',
        'presigned_urls' => 'presigned_urls'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_id' => 'setFileId',
        'mime_type' => 'setMimeType',
        'first_chunk_etag' => 'setFirstChunkEtag',
        'first_chunk_size_bytes' => 'setFirstChunkSizeBytes',
        'total_parts' => 'setTotalParts',
        'recommended_chunk_size' => 'setRecommendedChunkSize',
        'presigned_urls' => 'setPresignedUrls'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_id' => 'getFileId',
        'mime_type' => 'getMimeType',
        'first_chunk_etag' => 'getFirstChunkEtag',
        'first_chunk_size_bytes' => 'getFirstChunkSizeBytes',
        'total_parts' => 'getTotalParts',
        'recommended_chunk_size' => 'getRecommendedChunkSize',
        'presigned_urls' => 'getPresignedUrls'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('file_id', $data ?? [], null);
        $this->setIfExists('mime_type', $data ?? [], null);
        $this->setIfExists('first_chunk_etag', $data ?? [], null);
        $this->setIfExists('first_chunk_size_bytes', $data ?? [], null);
        $this->setIfExists('total_parts', $data ?? [], null);
        $this->setIfExists('recommended_chunk_size', $data ?? [], null);
        $this->setIfExists('presigned_urls', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['file_id'] === null) {
            $invalidProperties[] = "'file_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/", $this->container['file_id'])) {
            $invalidProperties[] = "invalid value for 'file_id', must be conform to the pattern /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.";
        }

        if ($this->container['mime_type'] === null) {
            $invalidProperties[] = "'mime_type' can't be null";
        }
        if ($this->container['first_chunk_etag'] === null) {
            $invalidProperties[] = "'first_chunk_etag' can't be null";
        }
        if ($this->container['first_chunk_size_bytes'] === null) {
            $invalidProperties[] = "'first_chunk_size_bytes' can't be null";
        }
        if ($this->container['total_parts'] === null) {
            $invalidProperties[] = "'total_parts' can't be null";
        }
        if (($this->container['total_parts'] > 500)) {
            $invalidProperties[] = "invalid value for 'total_parts', must be smaller than or equal to 500.";
        }

        if (($this->container['total_parts'] < 2)) {
            $invalidProperties[] = "invalid value for 'total_parts', must be bigger than or equal to 2.";
        }

        if ($this->container['recommended_chunk_size'] === null) {
            $invalidProperties[] = "'recommended_chunk_size' can't be null";
        }
        if (($this->container['recommended_chunk_size'] > 104857600)) {
            $invalidProperties[] = "invalid value for 'recommended_chunk_size', must be smaller than or equal to 104857600.";
        }

        if (($this->container['recommended_chunk_size'] < 5242880)) {
            $invalidProperties[] = "invalid value for 'recommended_chunk_size', must be bigger than or equal to 5242880.";
        }

        if ($this->container['presigned_urls'] === null) {
            $invalidProperties[] = "'presigned_urls' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_id
     *
     * @return string
     */
    public function getFileId()
    {
        return $this->container['file_id'];
    }

    /**
     * Sets file_id
     *
     * @param string $file_id UUID v7 format identifier (time-ordered)
     *
     * @return self
     */
    public function setFileId($file_id)
    {
        if (is_null($file_id)) {
            throw new \InvalidArgumentException('non-nullable file_id cannot be null');
        }

        if ((!preg_match("/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/", ObjectSerializer::toString($file_id)))) {
            throw new \InvalidArgumentException("invalid value for \$file_id when calling MultipartInitiateResponse., must conform to the pattern /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.");
        }

        $this->container['file_id'] = $file_id;

        return $this;
    }

    /**
     * Gets mime_type
     *
     * @return string
     */
    public function getMimeType()
    {
        return $this->container['mime_type'];
    }

    /**
     * Sets mime_type
     *
     * @param string $mime_type MIME type detected from the first chunk
     *
     * @return self
     */
    public function setMimeType($mime_type)
    {
        if (is_null($mime_type)) {
            throw new \InvalidArgumentException('non-nullable mime_type cannot be null');
        }
        $this->container['mime_type'] = $mime_type;

        return $this;
    }

    /**
     * Gets first_chunk_etag
     *
     * @return string
     */
    public function getFirstChunkEtag()
    {
        return $this->container['first_chunk_etag'];
    }

    /**
     * Sets first_chunk_etag
     *
     * @param string $first_chunk_etag ETag of the first chunk stored as S3 part 1
     *
     * @return self
     */
    public function setFirstChunkEtag($first_chunk_etag)
    {
        if (is_null($first_chunk_etag)) {
            throw new \InvalidArgumentException('non-nullable first_chunk_etag cannot be null');
        }
        $this->container['first_chunk_etag'] = $first_chunk_etag;

        return $this;
    }

    /**
     * Gets first_chunk_size_bytes
     *
     * @return int
     */
    public function getFirstChunkSizeBytes()
    {
        return $this->container['first_chunk_size_bytes'];
    }

    /**
     * Sets first_chunk_size_bytes
     *
     * @param int $first_chunk_size_bytes Size of the first chunk received (for client validation)
     *
     * @return self
     */
    public function setFirstChunkSizeBytes($first_chunk_size_bytes)
    {
        if (is_null($first_chunk_size_bytes)) {
            throw new \InvalidArgumentException('non-nullable first_chunk_size_bytes cannot be null');
        }
        $this->container['first_chunk_size_bytes'] = $first_chunk_size_bytes;

        return $this;
    }

    /**
     * Gets total_parts
     *
     * @return int
     */
    public function getTotalParts()
    {
        return $this->container['total_parts'];
    }

    /**
     * Sets total_parts
     *
     * @param int $total_parts Total number of parts. The client slices the remaining file into exactly (total_parts - 1) chunks using recommended_chunk_size. The last chunk may be smaller.
     *
     * @return self
     */
    public function setTotalParts($total_parts)
    {
        if (is_null($total_parts)) {
            throw new \InvalidArgumentException('non-nullable total_parts cannot be null');
        }

        if (($total_parts > 500)) {
            throw new \InvalidArgumentException('invalid value for $total_parts when calling MultipartInitiateResponse., must be smaller than or equal to 500.');
        }
        if (($total_parts < 2)) {
            throw new \InvalidArgumentException('invalid value for $total_parts when calling MultipartInitiateResponse., must be bigger than or equal to 2.');
        }

        $this->container['total_parts'] = $total_parts;

        return $this;
    }

    /**
     * Gets recommended_chunk_size
     *
     * @return int
     */
    public function getRecommendedChunkSize()
    {
        return $this->container['recommended_chunk_size'];
    }

    /**
     * Sets recommended_chunk_size
     *
     * @param int $recommended_chunk_size Chunk size in bytes for remaining parts. Calculated from first chunk throughput * 5s target, clamped to 5MB-100MB. The last chunk may be smaller than 5MB.
     *
     * @return self
     */
    public function setRecommendedChunkSize($recommended_chunk_size)
    {
        if (is_null($recommended_chunk_size)) {
            throw new \InvalidArgumentException('non-nullable recommended_chunk_size cannot be null');
        }

        if (($recommended_chunk_size > 104857600)) {
            throw new \InvalidArgumentException('invalid value for $recommended_chunk_size when calling MultipartInitiateResponse., must be smaller than or equal to 104857600.');
        }
        if (($recommended_chunk_size < 5242880)) {
            throw new \InvalidArgumentException('invalid value for $recommended_chunk_size when calling MultipartInitiateResponse., must be bigger than or equal to 5242880.');
        }

        $this->container['recommended_chunk_size'] = $recommended_chunk_size;

        return $this;
    }

    /**
     * Gets presigned_urls
     *
     * @return \Gisl\Generated\OpenApi\Model\PresignedUrlPart[]
     */
    public function getPresignedUrls()
    {
        return $this->container['presigned_urls'];
    }

    /**
     * Sets presigned_urls
     *
     * @param \Gisl\Generated\OpenApi\Model\PresignedUrlPart[] $presigned_urls Pre-signed S3 PUT URLs for parts 2 through total_parts. Each URL accepts a PUT request with raw chunk bytes as body. Collect the ETag from each S3 response for the complete request.
     *
     * @return self
     */
    public function setPresignedUrls($presigned_urls)
    {
        if (is_null($presigned_urls)) {
            throw new \InvalidArgumentException('non-nullable presigned_urls cannot be null');
        }
        $this->container['presigned_urls'] = $presigned_urls;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


