<?php
/**
 * OperationType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * OperationType Class Doc Comment
 *
 * @category Class
 * @description Available operation types: - compress: Reduce file size (images, audio, video, documents) - thumbnail: Generate preview image (images, video, documents) - watermark: Apply branding/protection (images, video, audio, documents) - merge: Concatenate/combine multiple files into one (images, video, audio, documents/PDF). Multi-input. - archive: Bundle files into ZIP/tar.gz (all types). Multi-input. - convert: Change file format (all types)
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperationType
{
    /**
     * Possible values of this enum
     */
    public const COMPRESS = 'compress';

    public const THUMBNAIL = 'thumbnail';

    public const WATERMARK = 'watermark';

    public const MERGE = 'merge';

    public const ARCHIVE = 'archive';

    public const CONVERT = 'convert';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COMPRESS,
            self::THUMBNAIL,
            self::WATERMARK,
            self::MERGE,
            self::ARCHIVE,
            self::CONVERT
        ];
    }
}


