<?php
/**
 * OperationType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * OperationType Class Doc Comment
 *
 * @category Class
 * @description Available operation types: - compress: Reduce file size (images, audio, video, documents) - thumbnail: Legacy thumbnail value. Generates a preview image   for any media type via a single Lambda. Currently the only   thumbnail value the compression_api publisher emits; retirement   is planned after the publisher adopts the four sub-type values   below in a follow-up API PR. - thumbnail_image: Image thumbnail sub-type. Backed by a dedicated   Rust image Lambda. Not yet emitted by the publisher. - thumbnail_video: Video thumbnail sub-type. Backed by a dedicated   FFmpeg Lambda. Not yet emitted. - thumbnail_document: PDF/EPUB thumbnail sub-type. Backed by a   dedicated Ghostscript Lambda. Not yet emitted. - thumbnail_office: Office document (DOCX/XLSX/PPTX/ODT/ODS/ODP)   thumbnail sub-type. Backed by a dedicated LibreOffice Lambda.   Not yet emitted. - watermark: Apply branding/protection (images only) - merge: Concatenate/combine multiple files into one (images, video, audio, documents/PDF). Multi-input. - archive: Bundle files into ZIP/tar.gz (all types). Multi-input. - convert: Change file format (all types)  Both the legacy &#x60;thumbnail&#x60; value and the four sub-type values are valid routing targets today during the thumbnail migration window. See &#x60;asyncapi/events.yaml&#x60; for the full routing vocabulary and the publisher branching rule.
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperationType
{
    /**
     * Possible values of this enum
     */
    public const COMPRESS = 'compress';

    public const THUMBNAIL = 'thumbnail';

    public const THUMBNAIL_IMAGE = 'thumbnail_image';

    public const THUMBNAIL_VIDEO = 'thumbnail_video';

    public const THUMBNAIL_DOCUMENT = 'thumbnail_document';

    public const THUMBNAIL_OFFICE = 'thumbnail_office';

    public const WATERMARK = 'watermark';

    public const MERGE = 'merge';

    public const ARCHIVE = 'archive';

    public const CONVERT = 'convert';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COMPRESS,
            self::THUMBNAIL,
            self::THUMBNAIL_IMAGE,
            self::THUMBNAIL_VIDEO,
            self::THUMBNAIL_DOCUMENT,
            self::THUMBNAIL_OFFICE,
            self::WATERMARK,
            self::MERGE,
            self::ARCHIVE,
            self::CONVERT
        ];
    }
}


