<?php
/**
 * SseEventType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * SseEventType Class Doc Comment
 *
 * @category Class
 * @description Server-Sent Event types pushed on the /events endpoint: - operation.progress: Progress update for an operation - operation.completed: Operation finished successfully - operation.failed: Operation encountered an error - job.completed: All operations in a job completed - job.failed: Job failed - workflow.completed: All jobs completed successfully - workflow.failed: All jobs finished, at least one failed - workflow.partially_failed: Some succeeded, some failed
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SseEventType
{
    /**
     * Possible values of this enum
     */
    public const OPERATION_PROGRESS = 'operation.progress';

    public const OPERATION_COMPLETED = 'operation.completed';

    public const OPERATION_FAILED = 'operation.failed';

    public const JOB_COMPLETED = 'job.completed';

    public const JOB_FAILED = 'job.failed';

    public const WORKFLOW_COMPLETED = 'workflow.completed';

    public const WORKFLOW_FAILED = 'workflow.failed';

    public const WORKFLOW_PARTIALLY_FAILED = 'workflow.partially_failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPERATION_PROGRESS,
            self::OPERATION_COMPLETED,
            self::OPERATION_FAILED,
            self::JOB_COMPLETED,
            self::JOB_FAILED,
            self::WORKFLOW_COMPLETED,
            self::WORKFLOW_FAILED,
            self::WORKFLOW_PARTIALLY_FAILED
        ];
    }
}


