<?php
/**
 * WorkflowCreateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GISL Compression API
 *
 * REST API for the GISL (Give It Smaller) file compression and processing service.  **Architecture:** - Upload files to get a `file_id` - Create workflows referencing uploaded files with operations (compress, thumbnail, watermark, merge, archive, convert) - Poll status, stream SSE events, or receive webhook callbacks - Download results per operation output  **Response envelope:** All mutation and query endpoints return `{ success: true, data: {...} }` on success and `{ success: false, error: \"...\", details: [...] }` on failure. Exceptions: `GET /api/operations/schema` returns raw JSON (CDN-cacheable), health probes return flat objects, and `POST /api/contact` returns 204 with no body.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gisl\Generated\OpenApi\Model;

use \ArrayAccess;
use \Gisl\Generated\OpenApi\ObjectSerializer;

/**
 * WorkflowCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  Gisl\Generated\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WorkflowCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WorkflowCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'jobs' => '\Gisl\Generated\OpenApi\Model\JobDefinition[]',
        'workflow_edges' => '\Gisl\Generated\OpenApi\Model\WorkflowEdge[]',
        'callback_url' => 'string',
        'callback_events' => '\Gisl\Generated\OpenApi\Model\CallbackEventType[]',
        'export' => '\Gisl\Generated\OpenApi\Model\ExportConfig'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'jobs' => null,
        'workflow_edges' => null,
        'callback_url' => 'uri',
        'callback_events' => null,
        'export' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'jobs' => false,
        'workflow_edges' => false,
        'callback_url' => true,
        'callback_events' => false,
        'export' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'jobs' => 'jobs',
        'workflow_edges' => 'workflow_edges',
        'callback_url' => 'callback_url',
        'callback_events' => 'callback_events',
        'export' => 'export'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'jobs' => 'setJobs',
        'workflow_edges' => 'setWorkflowEdges',
        'callback_url' => 'setCallbackUrl',
        'callback_events' => 'setCallbackEvents',
        'export' => 'setExport'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'jobs' => 'getJobs',
        'workflow_edges' => 'getWorkflowEdges',
        'callback_url' => 'getCallbackUrl',
        'callback_events' => 'getCallbackEvents',
        'export' => 'getExport'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('jobs', $data ?? [], null);
        $this->setIfExists('workflow_edges', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('callback_events', $data ?? [], null);
        $this->setIfExists('export', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['jobs'] === null) {
            $invalidProperties[] = "'jobs' can't be null";
        }
        if ((count($this->container['jobs']) < 1)) {
            $invalidProperties[] = "invalid value for 'jobs', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['callback_url']) && !preg_match("/^https:\/\//", $this->container['callback_url'])) {
            $invalidProperties[] = "invalid value for 'callback_url', must be conform to the pattern /^https:\/\//.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets jobs
     *
     * @return \Gisl\Generated\OpenApi\Model\JobDefinition[]
     */
    public function getJobs()
    {
        return $this->container['jobs'];
    }

    /**
     * Sets jobs
     *
     * @param \Gisl\Generated\OpenApi\Model\JobDefinition[] $jobs List of jobs in this workflow
     *
     * @return self
     */
    public function setJobs($jobs)
    {
        if (is_null($jobs)) {
            throw new \InvalidArgumentException('non-nullable jobs cannot be null');
        }


        if ((count($jobs) < 1)) {
            throw new \InvalidArgumentException('invalid length for $jobs when calling WorkflowCreateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['jobs'] = $jobs;

        return $this;
    }

    /**
     * Gets workflow_edges
     *
     * @return \Gisl\Generated\OpenApi\Model\WorkflowEdge[]|null
     */
    public function getWorkflowEdges()
    {
        return $this->container['workflow_edges'];
    }

    /**
     * Sets workflow_edges
     *
     * @param \Gisl\Generated\OpenApi\Model\WorkflowEdge[]|null $workflow_edges DAG dependency edges between jobs. Each edge defines that a downstream job depends on an upstream job's output. Jobs with no incoming edges start immediately. Jobs with dependencies wait for all upstream jobs.
     *
     * @return self
     */
    public function setWorkflowEdges($workflow_edges)
    {
        if (is_null($workflow_edges)) {
            throw new \InvalidArgumentException('non-nullable workflow_edges cannot be null');
        }
        $this->container['workflow_edges'] = $workflow_edges;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url Webhook URL (HTTPS only). The API POSTs results to this URL when matching events occur. The payload includes workflow status, job results, and download URLs. Signed with HMAC (X-Signature header). Must use HTTPS to prevent credential leakage and SSRF against internal endpoints.
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            array_push($this->openAPINullablesSetToNull, 'callback_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('callback_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($callback_url) && (!preg_match("/^https:\/\//", ObjectSerializer::toString($callback_url)))) {
            throw new \InvalidArgumentException("invalid value for \$callback_url when calling WorkflowCreateRequest., must conform to the pattern /^https:\/\//.");
        }

        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets callback_events
     *
     * @return \Gisl\Generated\OpenApi\Model\CallbackEventType[]|null
     */
    public function getCallbackEvents()
    {
        return $this->container['callback_events'];
    }

    /**
     * Sets callback_events
     *
     * @param \Gisl\Generated\OpenApi\Model\CallbackEventType[]|null $callback_events Which events trigger the webhook callback. Defaults to terminal events only.
     *
     * @return self
     */
    public function setCallbackEvents($callback_events)
    {
        if (is_null($callback_events)) {
            throw new \InvalidArgumentException('non-nullable callback_events cannot be null');
        }
        $this->container['callback_events'] = $callback_events;

        return $this;
    }

    /**
     * Gets export
     *
     * @return \Gisl\Generated\OpenApi\Model\ExportConfig|null
     */
    public function getExport()
    {
        return $this->container['export'];
    }

    /**
     * Sets export
     *
     * @param \Gisl\Generated\OpenApi\Model\ExportConfig|null $export export
     *
     * @return self
     */
    public function setExport($export)
    {
        if (is_null($export)) {
            throw new \InvalidArgumentException('non-nullable export cannot be null');
        }
        $this->container['export'] = $export;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


